<a href="https://colab.research.google.com/github/KielKielKielKiel/LinearAlgebra_2ndSem/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra for CHE
## Laboratory 4 : Matrices


# Discussion

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

**Matrices**



$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$



#Latex form = $$

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\ 
C = \left\{
     \begin{array}\
       3x+5y-1z \\
       y+5z+4a+5b+9c \\
       -43x
      \end{array}\
\right. \\
$$



#Latex form = $$

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 3 & 5 & -1 \\ 0 & 1 & 5 \\ -43 & 0 & 0\end{bmatrix} 
$$


**Declaring Matrices**

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [2, 3, 1, 10],
    [5, 4, 9, 9]
])
describe_mat(A)


Matrix:
 [[ 2  3  1 10]
 [ 5  4  9  9]] 

Shape:	(2, 4)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [2, 3, 1, 10],
    [5, 4, 9, 9],
    [3, 4, 2, 1]
])
describe_mat(B)


Matrix:
 [[ 2  3  1 10]
 [ 5  4  9  9]
 [ 3  4  2  1]] 

Shape:	(3, 4)
Rank:	2



In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H) 

Matrix:
 [1 2 3 4 5] 

Shape:	(5,)
Rank:	1



#Categorizing Matrices

**Row and Column Matrices**

In [ ]:
## declaring a row matrices

rowmatrix1 = np.array([
      1, 2, 3                 
]) ## this is a one dimensional comma, not a row matrix 
rowmatrix2 = np.array([
      [1, 2, 3]                 
]) ## a 2D Matrix with a shape of (1,3)
describe_mat(rowmatrix1)
describe_mat(rowmatrix2)

Matrix:
 [1 2 3] 

Shape:	(3,)
Rank:	1

Matrix:
 [[1 2 3]] 

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a column Matrix

Colum1 = np.array([
               [2],
               [3]    
]) 
describe_mat(Colum1)

Matrix:
 [[2]
 [3]] 

Shape:	(2, 1)
Rank:	2



In [ ]:
rowmatrix2 = np.array([
      [1, 2, 3]                 
]) 
Colum1 = np.array([
               [2],
               [3]    
]) 
describe_mat(Colum1) 
describe_mat(rowmatrix2)

Matrix:
 [[2]
 [3]] 

Shape:	(2, 1)
Rank:	2

Matrix:
 [[1 2 3]] 

Shape:	(1, 3)
Rank:	2



## Square Matrix

In [ ]:

def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')

In [ ]:
square_mat = np. array ([
        [1, 2],
        [3, 4]
])

non_s_m = np.array ([
         [1, 2],
         [3, 5],
         [5, 6]            
])
describe_mat(square_mat)
describe_mat(non_s_m)

Matrix:
 [[1 2]
 [3 4]] 

Shape:	(2, 2)
Rank:	2
Is Square:True

Matrix:
 [[1 2]
 [3 5]
 [5 6]] 

Shape:	(3, 2)
Rank:	2
Is Square:False



According to elemental values

# Null matrix

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs.Square:{is_square}\n')
  else:
    print('Matrix is NULL')

In [ ]:
nnull_matrix = np.array([ 0,2,3 ])
describe_mat (nnull_matrix)

IndexError: ignored

In [ ]:
null_matrix = np.array ([])
describe_mat(null_matrix)

Matrix is NULL


**Zero Matrix**

In [ ]:
zero_matr = np.zeros((3,22))
zero_mats = np.zeros((5,32))
zero_matrct = np.zeros((10,20))

print(f'Zero Row Matrix 1: \n {zero_matr}')
print(f'Zero Row Matrix 2: \n {zero_mats}')
print(f'Zero Row Matrix 3: \n {zero_matrct}')

Zero Row Matrix 1: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Row Matrix 2: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Row Matrix 3: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

**Ones Matrix**

In [ ]:
one_matr = np.ones((3,22))
one_mats = np.ones((5,4))
one_matrct = np.ones((10,20))

print(f'One Row Matrix 1: \n {one_matr}')
print(f'One Row Matrix 2: \n {one_mats}')
print(f'One Row Matrix 3: \n {one_matrct}')

One Row Matrix 1: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
One Row Matrix 2: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
One Row Matrix 3: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Diagonal Matrix**


In [ ]:
np.array ([
           [3,0,0],
           [0,4,0],
           [0,0,5]
])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [ ]:
diag = np.diag ([4,5,6,7,8,9,20])
diag.shape[0] == diag.shape[1]
diag

array([[ 4,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0, 20]])

**Identity Matrix**

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

** Upper Triangular Matrix **

In [ ]:
np.array ([
           [10,9,8,1,5],
           [0,6,5,1,4],
           [0,0,3,1,3],
           [0,0,0,1,2],
           [0,0,0,0,1]
])

array([[10,  9,  8,  1,  5],
       [ 0,  6,  5,  1,  4],
       [ 0,  0,  3,  1,  3],
       [ 0,  0,  0,  1,  2],
       [ 0,  0,  0,  0,  1]])

**Lower Triangle Matrix**

In [ ]:
np.array ([
       [1,2,3,4,0],
       [2,3,4,0,0],
       [1,2,0,0,0],
       [1,0,0,0,0]   

])

array([[1, 2, 3, 4, 0],
       [2, 3, 4, 0, 0],
       [1, 2, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

I = np.triu(G)
J = np.tril(G)
I

array([[1, 7, 8],
       [0, 2, 2],
       [0, 0, 7]])

In [ ]:
J

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

### Activity

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


$$
\theta = \begin{bmatrix} 5  &  3 & -1\end{bmatrix} \\
$$

In [ ]:
A1 = np.array ([5, 3, -1 ])
A1

array([ 5,  3, -1])

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


$$
A = \begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$

The matrix is square, with a rank of 2. It has a shape of (3, 3). It is also an upper triangular matrix.



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
A = \left\{\begin{array}
5x_1 + 7x_2 + 8x_3\\
2x_1 + 2x_2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H  ##lower tri [np.triu] for upper


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
A = \left\{\begin{array}
5x_1 \\
2x_1 + 2x_2 \\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

**Addition**

In [ ]:
A = np.array ([
              [1,2],
              [4,5]
])
B = np.array ([
              [1,2],
              [3,4]
])
A+B

array([[2, 4],
       [7, 9]])

In [ ]:
Summm = np.add(A, B) 
Summm

array([[2, 4],
       [7, 9]])

In [ ]:
A = np.array ([
              [1,2],
              [4,5]
])
10+A ## broadcasting

array([[11, 12],
       [14, 15]])

** Subraction**

In [ ]:
A = np.array ([
              [1,2],
              [4,5]
])
B = np.array ([
              [1,2],
              [3,4]
])
A-B

array([[0, 0],
       [1, 1]])

In [ ]:
Difff = np.subtract(A, B)
Difff

array([[0, 0],
       [1, 1]])

In [ ]:
A = np.array ([
              [1,2],
              [4,5]
])
B = np.array ([
              [1,2],
              [3,4]
])
3-B+A

array([[3, 3],
       [4, 4]])

##Element-Wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[ 1,  4],
       [12, 20]])

In [ ]:
2*A

array([[ 2,  4],
       [ 8, 10]])

In [ ]:
np.divide(A,B)


array([[1.        , 1.        ],
       [1.33333333, 1.25      ]])

In [ ]:
A/B

array([[1.        , 1.        ],
       [1.33333333, 1.25      ]])

###Activity

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
X = int(input("Number of rows:"))
Y = int(input("Number of columns:")) 
print("Entries per row (separated by space): ")  
entries = list(map(int, input().split()))

num_entries = len(entries)
area_dim = X*Y

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim != num_entries):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")

matrix = np.array(entries).reshape(X, Y)
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}')
describe_mat(matrix)
is_empty = matrix == 0
if False:
  print('The matrix is empty')
else:
   print('The matrix is not empty')

point=0
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if i == j and matrix[i][j] != 1:
            point=1 
            break
        elif i!=j and matrix[i][j]!=0:
            point=1
            break
if point==1:
    print("The matrix is not an identity matrix.")
else:
    print("The matrix is an identity matrix.")

arr = matrix
is_all_zero = np.all((arr == 0))
if is_all_zero:
    print('The matrix only have 0')
else:
    print('The matrix has non-zero items')

arr = matrix
is_all_zero = np.all((arr == 1))
if is_all_zero:
    print('The matrix only have 1')
else:
    print('The matrix non-ones items')

Number of rows:2
Number of columns:2
Entries per row (separated by space): 
1 1 2 2

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2
Is Square: True
The matrix is not empty
The matrix is not an identity matrix.
The matrix has non-zero items
The matrix non-ones items


In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
X = int(input("Number of rows for 1st Matrix: "))
Y = int(input("Number of columns for 1st Matrix: ")) 
print("Entries per row (separated by space): ")  
entries_1 = list(map(int, input().split()))
 
num_entries_1 = len(entries_1)
area_dim_1 = X*Y

def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n\n')

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_1 != num_entries_1):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")

matrix_1 = np.array(entries_1).reshape(X, Y)

describe_mat (matrix_1)
###############################################################################################################
A = int(input("Number of rows for 2nd Matrix: "))
B = int(input("Number of colums for 2nd Matrix: "))
print("Entries per row (separated by space): ")
entries_2 = list(map(int, input().split()))

num_entries_2 = len(entries_2)
area_dim_2 = A*B

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_2 != num_entries_2):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")

matrix_2 = np.array(entries_2).reshape(A, B)
describe_mat (matrix_2)
#################################################################################################################
dec_operation = input ("Enter Your Desired Operation (+,-,*,/) : ")
####################################ADDITION######################################################################
if dec_operation == '+' or dec_operation.lower() == "addition": 
  Matrix_sum = matrix_1 + matrix_2
  print("The Sum of the two Matrices are: \n{}".format(Matrix_sum))
####################################SUBTRACTION###################################################################
if dec_operation == '-' or dec_operation.lower() == "subtraction": 
  Matrix_diff = matrix_1 - matrix_2
  print("The Difference of the two Matrices are: \n{}".format(Matrix_diff))
####################################MULTIPLICATION################################################################
if dec_operation == '*' or dec_operation.lower() == "multiplication": 
  Matrix_prod = matrix_1 * matrix_2
  print("The Product of the two Matrices are: \n{}".format(Matrix_prod))
#####################################DIVISION#####################################################################
if dec_operation == '/' or dec_operation.lower() == "division": 
  Matrix_quo = matrix_1 / matrix_2
  print("The Quotient of the two Matrices are: \n{}".format(Matrix_quo))
##################################################################################################################



Number of rows for 1st Matrix: 2
Number of columns for 1st Matrix: 2
Entries per row (separated by space): 
1 1 1 1

Matrix:
[[1 1]
 [1 1]]

Shape:	(2, 2)
Rank:	2
Is Square: True


Number of rows for 2nd Matrix: 2
Number of colums for 2nd Matrix: 2
Entries per row (separated by space): 
1 1 1 1

Matrix:
[[1 1]
 [1 1]]

Shape:	(2, 2)
Rank:	2
Is Square: True


Enter Your Desired Operation (+,-,*,/) : a
Invalid Operation
