<a href="https://colab.research.google.com/github/KielKielKielKiel/LinearAlgebra_2ndSem/blob/main/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Laboratory 6: Matrix Operaions

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

using np.transpose ()

In [ ]:
A = np.array ([
     [1, 2, 3],
     [500, -1, 2],
     [2, 6, 1]
])
A

array([[  1,   2,   3],
       [500,  -1,   2],
       [  2,   6,   1]])

In [ ]:
Atran = np.transpose(A)
Atran

array([[  1, 500,   2],
       [  2,  -1,   6],
       [  3,   2,   1]])

In [ ]:
Atraneq = A.T
Atraneq

array([[  1, 500,   2],
       [  2,  -1,   6],
       [  3,   2,   1]])

In [ ]:
np.array_equiv(Atran, Atraneq)

True

In [ ]:
B = np.array ([
               [1,2,3,2],
               [0,1,42,5],
               [1,5,1,3]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.                             shape

(4, 3)

## Dot Product / Inner Product

In [ ]:
First = np.array ([
               [3,4,5],
               [3,5,2],
               [2,4,1]
])
Second = np.array ([
                    [1,2],
                    [4,5],
                    [7,7]
])

In [ ]:
np.array_equiv(First, Second)

False

In [ ]:
First.dot(Second)

array([[54, 61],
       [37, 45],
       [25, 31]])

In [ ]:
np.matmul(First, Second)

array([[54, 61],
       [37, 45],
       [25, 31]])

In [ ]:
First @ Second

array([[54, 61],
       [37, 45],
       [25, 31]])

###Rule 1 : The inner dimensions of the two matrices in question must be the same.

In [ ]:
D = np.array ([
               [3,1,1.5],
               [1,5,2.1],
               [3.5, 6.7, 23]
])
D.shape

(3, 3)

In [ ]:
A = np.array([
    [1, 3,5,7],
    [5, 2,4,6],
    [12, 90,1,0]
])
B = np.array([
    [23,2,5,1],
    [1.2,3.5,6,0],
    [-1,-2,7,0] 
])
C = np.array([
    [0,12,5],
    [0,5,0],
    [3,4,2],
    [1,2,3]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 4)
(3, 4)
(4, 3)


In [ ]:
A @ C

array([[ 22,  61,  36],
       [ 18,  98,  51],
       [  3, 598,  62]])

In [ ]:
B @ C

array([[ 16. , 308. , 128. ],
       [ 18. ,  55.9,  18. ],
       [ 21. ,   6. ,   9. ]])

###Rule 2: Dot Product has special properties

1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$


In [ ]:
A = np.array([
    [1,2,3,4],
    [4,5,6,5],
    [7,8,9,6],
    [1,2,3,4]
])
B = np.array([
    [0,0,0,1],
    [0,0,3,7],
    [0,4,8,5],
    [1,2,3,4]
])
C = np.array([
    [1,6,0,1],
    [0,2,2,12],
    [1,4,5,13],
    [1,3,2,1]
])

In [ ]:
E = A.dot(B)
E2 = A.dot(C)
F = B.dot(C)
G = B + C
H = E + E2

In [ ]:
I = B.dot(A)
J = C.dot(A)
K = I + J

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equiv(A.dot(B), A.dot(A))

False

In [ ]:
np.array_equiv(A.dot(F), E.dot(C))

True

In [ ]:
np.array_equiv(A.dot(G), H)

True

In [ ]:
np.array_equiv(G.dot(A), K)

True

In [ ]:
A.dot(1)


array([[1, 2, 3, 4],
       [4, 5, 6, 5],
       [7, 8, 9, 6],
       [1, 2, 3, 4]])

In [ ]:
A.dot(0)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

##Determinants

it should be square matrix (np.linalg.det())

In [ ]:
A = np.array([
    [1,2,3,4],
    [4,5,6,5],
    [7,8,9,6],
    [1,2,2,4]
])
B = np.array([
    [0,5,0,],
    [1,0,3,],
    [0,4,8,]
    
])
C = np.array([
    [1,6],
    [0,2]
])


In [ ]:
X = np.linalg.det(A)
X

0.0

In [ ]:
Y = np.linalg.det(B)
Y

-39.99999999999998

In [ ]:
Z = np.linalg.det(C)
Z

2.0

##INVERSE

It should be square matrix (np.linalg.inv())

In [ ]:
Try = np.array([
    [5,6],
    [1,-5]
])

np.array(Try @ np.linalg.inv(Try), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
A = np.array([
    [1,2,3,4],
    [4,-5,6,5],
    [7,8,-9,6],
    [1,-2,2,4]
])
B = np.array([
    [0,5,0,],
    [1,0,3,],
    [0,4,8,]
    
])
C = np.array([
    [1,6],
    [0,2]
])


In [ ]:
Xa = np.linalg.inv(A)
Xa

array([[-0.03359684,  0.23320158,  0.06521739, -0.35573123],
       [ 0.20652174, -0.02173913,  0.01086957, -0.19565217],
       [ 0.17391304,  0.08695652, -0.04347826, -0.2173913 ],
       [ 0.02470356, -0.11264822,  0.01086957,  0.34980237]])

In [ ]:
Yb = np.linalg.inv(B)
Yb

array([[ 0.3  ,  1.   , -0.375],
       [ 0.2  ,  0.   ,  0.   ],
       [-0.1  ,  0.   ,  0.125]])

In [ ]:
Zc = np.linalg.inv(C)
Zc

array([[ 1. , -3. ],
       [ 0. ,  0.5]])

In [ ]:
B = np.array([
    [0,-5,0,],
    [1,0,-3,],
    [0,-4,8,]
])
Binv = np.linalg.inv(B)
Binv

array([[-0.3  ,  1.   ,  0.375],
       [-0.2  , -0.   , -0.   ],
       [-0.1  ,  0.   ,  0.125]])

In [ ]:
B @ Binv

array([[-1.  ,  0.  ,  0.  ],
       [-0.6 ,  1.  ,  0.75],
       [-1.6 ,  0.  ,  1.  ]])